# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "My awesome app"
      lane :distribute do
          build_android_app(task: "assembleRelease") # build_android_app is a built-in fastlane action.

          firebase_app_distribution(
              app: "1:520602086364:android:eda14b199b7041e33a3d19",
              firebase_cli_token: "1//0eVLDgw6L_fk1CgYIARAAGA4SNwF-L9IrgIbvLu8oOEdvsQYE1ftCMra-orEsMLIRpsECDe_-W5laWOFVvXnExvvyUhiPb6QbU5g",
              testers: "qkrwpgud1121@gmail.com",
              release_notes: "APK 파싱 실패"
          )
      end
end
